[settings]
  soupault_version = "4.11.0"
  clean_urls = true
  debug = false
  generator_mode = true
  pretty_print_html = true
  strict = true
  verbose = true
  page_character_encoding = "utf-8"
  doctype = "<!DOCTYPE html>"
  complete_page_selector = "html"
  site_dir = "pages"
  build_dir = "outputs"
  page_file_extensions = ["html", "md"]
  keep_extensions = ["html"]
  default_content_action = "append_child"
  default_content_selector = "main"
  default_extension = "html"
  default_template_file = "templates/main.html"
 
[preprocessors]
  md = "pandoc -f commonmark+smart -t html"

[widgets.insert-footer]
  widget = "include"
  selector = "body"
  action = "append_child"
  file = "templates/footer.html"

[widgets.no-blink]
  widget = "delete_element"
  selector = "blink"
  delete_all = true

[widgets.page-title]
  widget = "title"
  selector = "h1"
  force = true
